### ISSUE TITLE
Sed recursion

### ISSUE THREAD

**Issue by timvisee** [ndri/reddit-sedbot#1]
I came across your bot on Reddit in a [/r/linuxmasterrace](http://reddit.com/r/linuxmasterrace) thread.

The first thing I thought was that I had to try recursion.

After a quick dirty test (which is not infinite loopable on purpose), I figured recursion was possible.

Yes, as far as I can see it is possible to create infinite loops with this. I won't try it out however. I assume this isn't a feature, therefore I think it must be patched as soon as possible to prevent abuse.

[Here's a link to my recursion comment](http://reddit.com/r/linuxmasterrace/comments/7i5j30/good_news_from_steam_3/dqwnqss).

I thought it would be nice to update you about this.

timvisee

**Comment by ndri** [comment]
Huge thanks! I made it so the bot wouldn't respond to its own comments.

**Comment by timvisee** [comment]
Awesome you were able to fix it so quickly.

Keep up the awesome work!
